abstract: Query web search engines and get URLs
author: Martin Thurn <mthurn@cpan.org>
build_requires:
  ExtUtils::MM_Unix: 1.41
  File::Spec: 0
  File::Temp: 0
  IO::Capture::Stderr: 0
  Pod::Tests: 0.12
  Test::File: 0
  Test::Inline: 2
  Test::More: 0
  Test::Pod: 0
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: WWW-Search
no_index:
  directory:
    - inc
    - t
recommends:
  Email::MIME: 0
  Email::MIME::Creator: 0
  Email::Send: 0
  Email::Send::SMTP::Auth: 0
requires:
  Data::Dumper: 0
  Date::Manip: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  Getopt::Long: 2.24
  HTML::Parser: 2.23
  HTML::TreeBuilder: 0
  LWP::UserAgent: 2
  Net::Domain: 0
  POSIX: 0
  Pod::Usage: 0
  URI: 0
  URI::Escape: 0
  User: 0
  perl: 5.004
version: 2.486
