---
abstract: 'Virtual base class for WWW searches'
author:
  - 'John Heidemann <johnh@isi.edu>'
build_requires:
  ExtUtils::MM_Unix: 1.41
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  IO::Capture::Stderr: 0
  Test::File: 0
  Test::More: 0
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Search
name: WWW-Search
no_index:
  directory:
    - inc
    - t
recommends:
  Email::MIME: 0
  Email::MIME::Creator: 0
  Email::Send: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Bit::Vector: 0
  CGI: 0
  Data::Dumper: 0
  Date::Manip: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  Getopt::Long: 2.24
  HTML::Parser: 2.23
  HTML::TreeBuilder: 0
  LWP::MemberMixin: 0
  LWP::UserAgent: 2
  Net::Domain: 0
  POSIX: 0
  Pod::Usage: 0
  Test::More: 0
  URI: 0
  URI::Escape: 0
  User: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 2.512
