---
abstract: 'Virtual base class for WWW searches'
author:
  - 'John Heidemann <johnh@isi.edu>'
build_requires:
  ExtUtils::MM_Unix: 1.41
  File::Spec: 0
  File::Temp: 0
  IO::Capture::Stderr: 0
  Test::File: 0
  Test::More: 0
  Test::Pod: 0
  Test::Simple: 0
distribution_type: module
generated_by: 'Module::Install version 0.70'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Search
no_index:
  directory:
    - inc
    - t
recommends:
  Email::MIME: 0
  Email::MIME::Creator: 0
  Email::Send: 0
requires:
  CGI: 0
  Data::Dumper: 0
  Date::Manip: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  Getopt::Long: 2.24
  HTML::Parser: 2.23
  HTML::TreeBuilder: 0
  LWP::MemberMixin: 0
  LWP::UserAgent: 2
  Net::Domain: 0
  POSIX: 0
  Pod::Usage: 0
  URI: 0
  URI::Escape: 0
  User: 0
  perl: 5.004
version: 2.497
