# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search
version:      2.44
version_from: 
installdirs:  site
requires:
    File::Basename:                0
    File::Find:                    0
    File::Spec:                    0
    Getopt::Long:                  2.24
    HTML::Parser:                  2.23
    HTML::TreeBuilder:             0
    LWP::UserAgent:                2
    MIME::Lite:                    0
    Net::Domain:                   0
    POSIX:                         0
    Test::Inline:                  0
    Test::More:                    0
    URI:                           0
    URI::Escape:                   0
    User:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
